apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: "my-kong"
  namespace: "x7jwz"
  annotations:
    renovate.tkp.hdi.dev/catalog: https://pg2000.github.io/tkp-app-catalog/
spec:
  name: argo-cd
  version: 4.3.0
  catalog: "hdi-catalog"
  config:
    configMap:
      name: "x7jwz-cluster-values"
      namespace: "x7jwz"

  namespace: "kong"
  kubeConfig:
    inCluster: false
  userConfig:
    configMap:
      name: "kong-user-values"
      namespace: "x7jwz"
